const ROUTES = {
    WELCOME: 'Welcome',
    WELCOME_NAVIGATOR: 'WelcomeNavigator',
    MOREINFO: 'MoreInfo',
    MOREINFO_NAVIGATOR: 'MoreInfoNavigator',
    HOME: 'Home',
    HOME_NAVIGATOR: 'HomeNavigator',
    SEARCH: 'Search',
    SEARCH_NAVIGATOR: 'SearchNavigator',
    POST: 'Post',
    POST_NAVIGATOR: 'PostNavigator',
    NOTIFICATION: 'Notification',
    NOTIFICATION_NAVIGATOR: 'NotificationNavigator',
    PROFILE: 'Profile',
    PROFILE_NAVIGATOR: 'ProfileNavigator',
    SETTING: 'Setting',
    SETTING_NAVIGATOR: 'SettingNavigator',
    UPDATEPROFILE: 'UpdateProfile',
    UPDATEPROFILE_NAVIGATOR: 'UpdateProfileNavigator',
    CARTDETAIL: 'CartDetail',
    CARTDETAIL_NAVIGATOR: 'CartDetailNavigator',
    FRIENDS: 'Friends',
    FRIENDS_NAVIGATOR: 'FriendsNavigator',
    SETTINGFRIENDS: 'SettingFriends',
    SETTINGFRIENDS_NAVIGATOR: 'SettingFriendsNavigator',
    LISTFOLLOW: 'ListFollow',
    LISTFOLLOW_NAVIGATOR: 'ListFollowNavigator',

    LISTLIKE: 'ListLike',
    LISTLIKE_NAVIGATOR: 'ListLikeNavigator',

    HASHTAGVIEW: 'HashtagView',
    HASHTAGVIEW_NAVIGATOR: 'HashtagViewNavigator',
    SETTINGPACKAGE: 'SettingPackage',
    SETTINGPACKAGE_NAVIGATOR: 'SettingPackageNavigator',
    CHAT: 'Chat',
    CHAT_NAVIGATOR: 'ChatNavigator',
    REPORTUSER: 'ReportUser',
    REPORTUSER_NAVIGATOR: 'ReportUserNavigator',
    REPORTPOST: 'ReportPost',
    REPORTPOST_NAVIGATOR: 'ReportPostNavigator',
}
export default ROUTES;